class Scholar{
    constructor(first_name, last_name, class_of, classroom, project_name, group_members, project_profile_link, student_profile_link, presentation_format, past_award_winner){
        this.first_name = first_name;
        this.last_name = last_name;
        this.class_of = class_of;
        this.name_and_class_of = first_name + " " + last_name + " '" + class_of.substring(2);
        this.classroom = classroom;
        this.project_name = project_name;
        this.group_members = group_members;
        this.project_profile_link = project_profile_link;
        this.student_profile_link = student_profile_link;
        this.presentation_format = presentation_format;
        this.past_award_winner = past_award_winner;
    }
}

// Last updated 20 May 2024
// Order will determine result order, best to sort alphabetically by last name
const i2_scholars = [
    new Scholar("Adam", "Abuzaid", "2029", "813", "AI & Water Use The Hidden Cost", 1, "", "", "DPD", false),
    new Scholar("Nico", "Aldaz", "2027", "812", "AquaMark", 1, "", "", "DPD", false),
    new Scholar("Thaze", "Antonio", "2029", "703", "Power Players", 2, "", "", "DPD", false),
    new Scholar("George", "Arriola", "2027", "Outside 803", "Avoiding Avoidance", 1, "", "", "IO", false),
    new Scholar("Jude", "Bandak", "2028", "805", "Rehab-AI", 2, "", "", "DPD", false),
    new Scholar("August", "Bastian", "2028", "802", "Arrow Tracking from Video", 1, "", "", "IO", false),
    new Scholar("Montserrat", "Batchelli-Hennessey", "2029", "804", "Pollination Sustainability", 1, "", "", "IO", false),
    new Scholar("Kieran", "Batchelli-Hennessey", "2027", "809", "IPABrew", 2, "", "", "DPD", false),
    new Scholar("Esme", "Bautista", "2028", "814", "Novita - A Modern Way to Reading", 1, "", "", "IO", false),
    new Scholar("Xavier", "Berenguer", "2029", "804", "Project Panic Button", 1, "", "", "DPD", false),
    new Scholar("Jackson", "Blossom", "2027", "703", "Carmageddon", 2, "", "", "DPD", false),
    new Scholar("Ava", "Bullitt", "2028", "811", "Time Flow", 2, "", "", "DPD", false),
    new Scholar("Jamila", "Bullock", "2028", "808", "Adaptify", 2, "", "", "DPD", true),
    new Scholar("Liam", "Calahan", "2028", "808", "Guitar Tab Transcriber", 1, "", "", "DPD", false),
    new Scholar("William (Liam)", "Cannon", "2027", "807", "Reef Wax", 1, "", "", "PPD", false),
    new Scholar("Lucas", "Carian", "2028", "812", "NewsFlow.ai", 3, "", "", "IO", false),
    new Scholar("Alexander", "Chang", "2027", "806", "Textbook Marketplace 2.0", 1, "", "", "IO", false),
    new Scholar("Andrew", "Chen", "2029", "810", "Flax Midplates: A Renewable Solution", 1, "", "", "PPD", false),
    new Scholar("Jacob", "Chew", "2028", "812", "NewsFlow.ai", 3, "", "", "DPD", false),
    new Scholar("Christina", "Chew", "2027", "803", "Fish Out of Water", 2, "", "", "DPD", false),
    new Scholar("Caylee", "Chin", "2028", "809", "Cypher Vision", 3, "", "", "DPD", false),
    new Scholar("Lola", "Clarke", "2028", "811", "Time Flow", 2, "", "", "DPD", false),
    new Scholar("Kaitlyn", "Cleaveland", "2029", "811", "TaskTogether", 1, "", "", "IO", false),
    new Scholar("Brayden", "Constantino", "2029", "814", "Stationary Bike Generator", 3, "", "", "IO", false),
    new Scholar("Fionn", "De Barra", "2027", "812", "EcoSortify", 2, "", "", "IO", false),
    new Scholar("Linhchi", "Doan", "2027", "806", "First Inventors", 1, "", "", "IO", false),
    new Scholar("Chase", "Dunn", "2027", "703", "Carmageddon", 2, "", "", "DPD", false),
    new Scholar("Charlotte", "Edwards", "2027", "802", "Bio-filtration device", 1, "", "", "PPD", false),
    new Scholar("Grayson", "Fong", "2029", "809", "Voice Directions Phone", 1, "", "", "PPD", false),
    new Scholar("Giovanna", "Fong", "2029", "803", "How Trees Affect the Weather", 1, "", "", "DPD", false),
    new Scholar("Darren", "Fung", "2028", "805", "Pill Sense", 2, "", "", "IO", true),
    new Scholar("Amelia", "Gumm", "2029", "803", "Sea Level Rise in San Francisco", 1, "", "", "IO", false),
    new Scholar("Logan", "Haber", "2027", "Outside 808", "SF Sports Facilities Research Project", 1, "", "", "IO", false),
    new Scholar("Jacob", "Hagenbeek", "2029", "814", "Stationary Bike Generator", 3, "", "", "IO", false),
    new Scholar("Brianna", "Hollub", "2028", "Outside 810", "AI Reality Check", 2, "", "", "IO", false),
    new Scholar("Elisha", "Huang", "2027", "804", "EcoSort", 1, "", "", "IO", false),
    new Scholar("Lucia", "Ibrahimovic", "2029", "814", "Reading’s Role as a Benefactor", 1, "", "", "IO", false),
    new Scholar("Piper", "Johnson", "2027", "803", "WaterWise", 1, "", "", "PPD", true),
    new Scholar("Brad", "Kaiser", "2028", "804", "Golf Tracker", 2, "", "", "PPD", false),
    new Scholar("Sydney", "Kerpelman", "2028", "807", "Cantelligence", 2, "", "", "PPD", false),
    new Scholar("Theo", "Koburov", "2029", "703", "Power Players", 2, "", "", "DPD", false),
    new Scholar("Amelia", "Kovalenko", "2029", "703", "One Step Forward, Two Steps Back", 2, "", "", "IO", false),
    new Scholar("Evan", "Kwong", "2029", "810", "Biogas", 1, "", "", "IO", false),
    new Scholar("Nico", "Laser", "2028", "804", "Golf Tracker", 2, "", "", "PPD", false),
    new Scholar("Julian", "Lechadores", "2028", "812", "FoundIt", 2, "", "", "DPD", false),
    new Scholar("Jaiden", "Leong", "2028", "805", "Pill Sense", 2, "", "", "PPD", false),
    new Scholar("Ava", "Lindner", "2028", "805", "The Digital Detox", 2, "", "", "DPD", false),
    new Scholar("Kara", "Liu", "2028", "809", "Cypher Vision", 3, "", "", "DPD", false),
    new Scholar("Dennis", "Liu", "2028", "812", "NewsFlow.ai", 3, "", "", "DPD", false),
    new Scholar("Nhi", "Ly", "2028", "810", "GreenThread", 3, "", "", "DPD", false),
    new Scholar("Riley", "Mak", "2029", "811", "Train to Last", 1, "", "", "IO", false),
    new Scholar("Abigail", "Manlapaz", "2028", "810", "GreenThread", 3, "", "", "IO", false),
    new Scholar("Philip", "Marinov", "2027", "809", "IPABrew", 2, "", "", "DPD", false),
    new Scholar("Robbie", "McKeown", "2028", "805", "Rehab-AI", 2, "", "", "DPD", false),
    new Scholar("Rye", "McMahon", "2027", "814", "Sky Visor", 1, "", "", "IO", false),
    new Scholar("Parker", "Mead", "2028", "805", "The Digital Detox", 2, "", "", "DPD", false),
    new Scholar("Diego", "Medina", "2029", "802", "BloomForge", 1, "", "", "IO", false),
    new Scholar("Eoin", "Merriman", "2029", "813", "Solar Panel Sweeper", 1, "", "", "IO", false),
    new Scholar("Tessa", "Miller-Wrong", "2028", "805", "Interactive Anatomy Model", 1, "", "", "PPD", false),
    new Scholar("Liya", "Milman", "2028", "Outside 810", "AI Reality Check", 2, "", "", "IO", false),
    new Scholar("Mason", "Mineses", "2029", "814", "Stationary Bike Generator", 3, "", "", "IO", false),
    new Scholar("Graham", "Moore", "2027", "812", "EcoSortify", 2, "", "", "IO", false),
    new Scholar("Katsy", "Morrow", "2029", "703", "One Step Forward, Two Steps Back", 2, "", "", "IO", false),
    new Scholar("Simone", "Myers", "2027", "805", "No Phone Simone", 1, "", "", "IO", false),
    new Scholar("Hudson", "Newhouse", "2027", "807", "Teach Reach", 1, "", "", "PPD", false),
    new Scholar("Margaret (Maggie)", "Orr", "2027", "810", "Algae Biofuel", 1, "", "", "IO", false),
    new Scholar("Shantanu (Shanti)", "Pai", "2027", "808", "Mantus", 1, "", "", "DPD", false),
    new Scholar("Ava", "Perez", "2027", "810", "Grown Packaging", 1, "", "", "IO", false),
    new Scholar("Luka", "Petkovic", "2028", "809", "AI Architecture with Dynamic Memory", 1, "", "", "DPD", false),
    new Scholar("Ryland", "Pugh", "2028", "802", "DriveGuide AI", 1, "", "", "IO", false),
    new Scholar("Danilo", "Quijano", "2029", "813", "Acoustic Energy Harvester", 1, "", "", "IO", false),
    new Scholar("Stephania", "Quinteros", "2028", "804", "A Hand For All", 1, "", "", "IO", false),
    new Scholar("Sharvi", "Rastogi", "2028", "807", "Smart Bird Feeder", 1, "", "", "PPD", false),
    new Scholar("Berlyn", "Ring", "2027", "804", "Hydrometric.", 1, "", "", "IO", false),
    new Scholar("Bram", "Salverda", "2027", "812", "AI Wildfire Prediction", 1, "", "", "IO", false),
    new Scholar("Neve", "Schmidt", "2029", "703", "Save Our Estuary", 1, "", "", "DPD", false),
    new Scholar("Anna", "Schou", "2028", "809", "Naitve", 1, "", "", "DPD", false),
    new Scholar("Samantha", "Shapiro", "2027", "803", "Fish Out of Water", 2, "", "", "DPD", false),
    new Scholar("Dash", "Snape", "2028", "807", "Cantelligence", 2, "", "", "PPD", false),
    new Scholar("Dagny", "Suro", "2027", "803", "Project Kelp", 2, "", "", "PPD", true),
    new Scholar("Rhyan", "Tagay", "2028", "810", "GreenThread", 3, "", "", "IO", false),
    new Scholar("Monico", "Tangaan", "2029", "811", "Recycling Right", 2, "", "", "IO", false),
    new Scholar("Calliope (Cali)", "Tangaan", "2027", "811", "Recycling Right", 2, "", "", "IO", false),
    new Scholar("Leo", "Thomson", "2027", "807", "Project Comfort Catch!", 1, "", "", "PPD", true),
    new Scholar("Emma", "Tom", "2028", "808", "Adaptify", 2, "", "", "IO", true),
    new Scholar("Oliver", "Waldin", "2027", "806", "Artificial Academics", 1, "", "", "IO", false),
    new Scholar("Justin", "Wang", "2029", "810", "Terra Clear", 1, "", "", "IO", false),
    new Scholar("Ashley", "Wang", "2027", "806", "Trash Talk", 1, "", "", "PPD", false),
    new Scholar("Lulu", "Ware", "2027", "803", "Project Kelp", 2, "", "", "PPD", false),
    new Scholar("Matthew", "Wells", "2027", "812", "AI Bias Analysis", 1, "", "", "IO", false),
    new Scholar("Evie", "Wiesler", "2029", "808", "Fabric Forward", 1, "", "", "DPD", false),
    new Scholar("Tesia", "Xu", "2027", "804", "SHC Spaces Reimagined", 1, "", "", "IO", false),
    new Scholar("Aiden", "Yang", "2029", "808", "Mind quest", 1, "", "", "DPD", false),
    new Scholar("Brendon", "Yang", "2029", "811", "Bin Scan", 1, "", "", "DPD", false),
    new Scholar("Rachel", "Zhao", "2028", "809", "Cypher Vision", 3, "", "", "DPD", false),
    new Scholar("Kyle", "Ching", "2028", "812", "FoundIt", 2, "", "", "DPD", false)
];